# Using Numpy for first time

Using for first time NumPy. Here we load numpy as np for practical uses. If we can find a detailed information of loading data files we can click on:
https://swcarpentry.github.io/r-novice-inflammation/01-starting-with-data/

In [1]:
import numpy as np

Numpy has a module called loadtxt which lets us to use data from a file (txt, cvs, etc) and read it. We can comment a line in python with the simbol #. The second argument, related with the delimiter, do mention about the separation symbol of data in our file. It means that if you have a file with numbers separated with a coma, you have to include de delimiter=',' in the second argument of module in order to avoid an error compilation.

In [2]:
data = np.loadtxt("data/inflammation-01.csv", delimiter=',')

In [3]:
data

array([[ 0.,  0.,  1.,  3.,  1.,  2.,  4.,  7.,  8.,  3.,  3.,  3., 10.,
         5.,  7.,  4.,  7.,  7., 12., 18.,  6., 13., 11., 11.,  7.,  7.,
         4.,  6.,  8.,  8.,  4.,  4.,  5.,  7.,  3.,  4.,  2.,  3.,  0.,
         0.],
       [ 0.,  1.,  2.,  1.,  2.,  1.,  3.,  2.,  2.,  6., 10., 11.,  5.,
         9.,  4.,  4.,  7., 16.,  8.,  6., 18.,  4., 12.,  5., 12.,  7.,
        11.,  5., 11.,  3.,  3.,  5.,  4.,  4.,  5.,  5.,  1.,  1.,  0.,
         1.],
       [ 0.,  1.,  1.,  3.,  3.,  2.,  6.,  2.,  5.,  9.,  5.,  7.,  4.,
         5.,  4., 15.,  5., 11.,  9., 10., 19., 14., 12., 17.,  7., 12.,
        11.,  7.,  4.,  2., 10.,  5.,  4.,  2.,  2.,  3.,  2.,  2.,  1.,
         1.],
       [ 0.,  0.,  2.,  0.,  4.,  2.,  2.,  1.,  6.,  7., 10.,  7.,  9.,
        13.,  8.,  8., 15., 10., 10.,  7., 17.,  4.,  4.,  7.,  6., 15.,
         6.,  4.,  9., 11.,  3.,  5.,  6.,  3.,  3.,  4.,  2.,  3.,  2.,
         1.],
       [ 0.,  1.,  1.,  3.,  3.,  1.,  3.,  5.,  2.,  4.,  4.,  7., 

If we need information about how to use a module of numpy, we can type the command help(np.name_of_module) such as:

In [4]:
help(np.loadtxt)

Help on function loadtxt in module numpy:

loadtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0, encoding='bytes', max_rows=None, *, like=None)
    Load data from a text file.
    
    Each row in the text file must have the same number of values.
    
    Parameters
    ----------
    fname : file, str, or pathlib.Path
        File, filename, or generator to read.  If the filename extension is
        ``.gz`` or ``.bz2``, the file is first decompressed. Note that
        generators should return byte strings.
    dtype : data-type, optional
        Data-type of the resulting array; default: float.  If this is a
        structured data-type, the resulting array will be 1-dimensional, and
        each row will be interpreted as an element of the array.  In this
        case, the number of columns used must match the number of fields in
        the data-type.
    comments : str or sequence of str, optional
  

The function shape can gives us the number of rows and columns of our file:

In [5]:
data.shape

(5, 40)

If we need to save these numbers we can use the code:

In [6]:
nrows, ncolumns = data.shape

In [7]:
print(nrows)

5


In [8]:
print(ncolumns)

40


Although our data are integer numbers, the module loadtxt save them as float of 64 bits. We can confirm this by typing:

In [9]:
print(data.dtype)

float64


We also can access to some data from our file, taking into account that our data is an array, using the command:

In [10]:
data[0]

array([ 0.,  0.,  1.,  3.,  1.,  2.,  4.,  7.,  8.,  3.,  3.,  3., 10.,
        5.,  7.,  4.,  7.,  7., 12., 18.,  6., 13., 11., 11.,  7.,  7.,
        4.,  6.,  8.,  8.,  4.,  4.,  5.,  7.,  3.,  4.,  2.,  3.,  0.,
        0.])

which prints the first row of the array, o we can access an especific data by: 

In [11]:
data[0,5]

2.0

Also, we can access to a determine range in our data by using ":" and the range from the first number to the last number plus one (it doesn't include the last number). 

In [12]:
data[0, 0:8]

array([0., 0., 1., 3., 1., 2., 4., 7.])

Finally, we can access by two (or three, or four, etc) data instead of one per one with:

In [13]:
data[0, 0:8:2]

array([0., 1., 1., 4.])

In [14]:
data[0, 0:8:3]

array([0., 3., 4.])

If we want to make an average of the data, we can use:

In [15]:
print(np.mean(data))

5.685


This code calculate the average of all numbers in our file, but if we need the average of only the row or the column we have to be more explicity:

In [16]:
print(nrows, ncolumns)
print(np.mean(data, axis=1))

5 40
[5.45  5.425 6.1   5.9   5.55 ]


As we can see, this code printed the average of each column because when we use axis=1 we tell to numpy that make an average over the columns and consider the rows constants. If we want to make an average over rows we can change axis=1 by axis=0:

In [17]:
print(nrows, ncolumns)
print(np.mean(data, axis=0))

5 40
[ 0.   0.6  1.4  2.   2.6  1.6  3.6  3.4  4.6  5.8  6.4  7.   6.8  7.4
  5.2  8.2  8.4 10.8  9.  11.6 13.8  9.8  9.6  9.4  9.  10.   8.8  5.6
  7.8  6.2  5.8  5.   4.4  3.6  3.   4.   1.8  1.8  0.8  0.8]


# List, Tuples and sets.

## List

Consider a list of subjects called courses, in which we are gonig to put five subjects as follow:

In [18]:
courses = ['History', 'Math', 'Chemistry', 'Physics', 'Biology']

If we want to know the number of elements into the array courses, or their size, we can use:

In [19]:
print(len(courses))

5


If we want to access to an specific element of the array, we have to put their position counting from the position cero (i.e for the first element the position is cero, the second one is the position one and so on). Also, if we want to access to the last element, we can use the label -1 (note that is equivalent to put [4] and [-1] in this example): 

In [20]:
print(courses[0])
print(courses[4])
print(courses[-1])

History
Biology
Biology


We can specify any range we want with the symbol : like in the next examples:

In [21]:
print(courses[0:2])
print(courses[:2])
print(courses[2:-1])
print(courses[2:])

['History', 'Math']
['History', 'Math']
['Chemistry', 'Physics']
['Chemistry', 'Physics', 'Biology']


To add a subject to courses array, we could use some functions that allows to include it into the array by putting it at last position (append), at first position (insert) or at determined position:

In [22]:
courses.append('Art')
print(courses)
courses.insert(0, 'Music')
print(courses)
courses.insert(3, 'Literature')
print(courses)

['History', 'Math', 'Chemistry', 'Physics', 'Biology', 'Art']
['Music', 'History', 'Math', 'Chemistry', 'Physics', 'Biology', 'Art']
['Music', 'History', 'Math', 'Literature', 'Chemistry', 'Physics', 'Biology', 'Art']


In [23]:
courses_2 = ['Electrodynamics', 'Quantum Mechanics']
courses.extend(courses_2)
print(courses)

['Music', 'History', 'Math', 'Literature', 'Chemistry', 'Physics', 'Biology', 'Art', 'Electrodynamics', 'Quantum Mechanics']


If we want to remove an element, we have the next options:

In [24]:
courses.remove('Biology')
print(courses)
courses.pop()
print(courses)

['Music', 'History', 'Math', 'Literature', 'Chemistry', 'Physics', 'Art', 'Electrodynamics', 'Quantum Mechanics']
['Music', 'History', 'Math', 'Literature', 'Chemistry', 'Physics', 'Art', 'Electrodynamics']


We have the option reverse, which organizes our array from the last element to the fist one, and the option sort, which organizes our array in alphabetic order:

In [25]:
courses.reverse()
print(courses)
courses.sort()
print(courses)

['Electrodynamics', 'Art', 'Physics', 'Chemistry', 'Literature', 'Math', 'History', 'Music']
['Art', 'Chemistry', 'Electrodynamics', 'History', 'Literature', 'Math', 'Music', 'Physics']


In [26]:
courses.sort(reverse=True)
print(courses)

['Physics', 'Music', 'Math', 'Literature', 'History', 'Electrodynamics', 'Chemistry', 'Art']


If we want to print a chain of string using the elements of the array courses, we can create a variable course_str and print the elements of courses with a separation of symbol - using the function join(). This prints a chain of strings which isn't an array. The opposite can be done by using the function split() and specifying the symbol separation used in the chain of strings, such as follow:

In [27]:
course_str = ' - '.join(courses)
print(course_str)
new_list = course_str.split(' - ')
print(new_list)

Physics - Music - Math - Literature - History - Electrodynamics - Chemistry - Art
['Physics', 'Music', 'Math', 'Literature', 'History', 'Electrodynamics', 'Chemistry', 'Art']


As an little example of a loop using for to print the courses in the array, we can type the next command line:

In [31]:
for index, course in enumerate(courses, start=1):
    print(index, course)

1 Physics
2 Music
3 Math
4 Literature
5 History
6 Electrodynamics
7 Chemistry
8 Art


## Tuples

Consider an array which is a list. In this case, we can use the same array courses but now we are going to call it as list_1. Lets define another list called list_2 as follow:

In [33]:
list_1 = ['History', 'Math', 'Physics', 'CompScy']
list_2 = list_1
print(list_1)
print(list_2)

['History', 'Math', 'Physics', 'CompScy']
['History', 'Math', 'Physics', 'CompScy']


As you can see, list_1 and list_2 are exactly the same array. If we want to modify an element of the list list_1, for example the first one, the first element of the list_2 is also modified:

In [34]:
list_1[0] = 'Art'
print(list_1)
print(list_2)

['Art', 'Math', 'Physics', 'CompScy']
['Art', 'Math', 'Physics', 'CompScy']


If you don't want to happen this, you can use a Tuple instead of list. The structure of a tuple is quite similar to the list but you have to use brackets () instead of []. If we do a similar procedure using tuples, the terminal will show an error because it is not posible to modify an element of a tuple as we do in a list: 

In [38]:
Tuple_1 = ('Art', 'Math', 'Physics', 'CompScy')
Tuple_2 = Tuple_1
print(Tuple_1)
print(Tuple_2)

Tuple_1[0] = 'Art'

print(Tuple_1)
print(Tuple_2)

('Art', 'Math', 'Physics', 'CompScy')
('Art', 'Math', 'Physics', 'CompScy')


TypeError: 'tuple' object does not support item assignment

## Sets

We can use sets using the brackets {}, and his elements can be printed in diferents orders because in a set doesn't matter the order of their elements. Also, we can add a repeated element and this will print only once per repeated element:

In [45]:
cs_courses = {'History', 'Math', 'Physics', 'CompScy', 'Math'}
print(cs_courses)
print(cs_courses)

{'Math', 'CompScy', 'Physics', 'History'}
{'Math', 'CompScy', 'Physics', 'History'}


We can also use common operations between sets as union, intersection, etc. Lets define another set and see how to works this operations:

In [47]:
art_courses = {'History', 'Math', 'Art', 'Design'}
print(cs_courses.intersection(art_courses))
print(cs_courses.difference(art_courses))
print(cs_courses.union(art_courses))

{'History', 'Math'}
{'CompScy', 'Physics'}
{'Design', 'Art', 'History', 'CompScy', 'Physics', 'Math'}


# Dictionaries: Working with key-values pairs

If you want to create a determined object which has diferent information about itself, you can use Dictionaries that uses Key-Values pairs. For example, we have objects called "student" and we want to provide it a name, an age and the courses. Thus, we have to type something like this:

In [14]:
student = {'name': 'John', 'age': 25, 'courses': ['Math', 'Physics'], 'Semester': '8'}
print(student)
print(student['name'])

{'name': 'John', 'age': 25, 'courses': ['Math', 'Physics'], 'Semester': '8'}
John


As you can see, we printed all the information and the name of the student. In any case, we can specify the key that we want to know or we can only access to all keys of the student. If we try to access to a key that is not define, as "phone", we would observe an error. If we want to avoid this error, we can use the function get() and this will print the message "None" by default:

In [15]:
print(student.get('name'))
print(student.get('phone'))

John
None


If we want to print a different message, like "Not Found", we can also specify it inside the function get():

In [16]:
print(student.get('phone', 'Not Found'))

Not Found


Also, we can add the key "phone" and his value by typing as follow:

In [17]:
student['phone'] = '555-5555'
print(student.get('phone', 'Not Found'))

555-5555


Sometimes, we will need to change a value, so we can change it using the brackects []:

In [18]:
student['name'] = 'Jane'
print(student)

{'name': 'Jane', 'age': 25, 'courses': ['Math', 'Physics'], 'Semester': '8', 'phone': '555-5555'}


It is usually used the function update() instead of [] to change some values of objects:

In [19]:
student.update({'name': 'Julie', 'age': '26', 'phone': '555-5555'})
print(student)

{'name': 'Julie', 'age': '26', 'courses': ['Math', 'Physics'], 'Semester': '8', 'phone': '555-5555'}


We can delete a key by using the command "del" that means delete something:

In [20]:
del student['Semester']
print(student)

{'name': 'Julie', 'age': '26', 'courses': ['Math', 'Physics'], 'phone': '555-5555'}


If we decide to remove a key but save the value, we can use the function pop as follow:

In [21]:
age = student.pop('age')
print(student)
print(age)

{'name': 'Julie', 'courses': ['Math', 'Physics'], 'phone': '555-5555'}
26


In [23]:
print(student.keys())
print(student.values())
print(student.items())

dict_keys(['name', 'courses', 'phone'])
dict_values(['Julie', ['Math', 'Physics'], '555-5555'])
dict_items([('name', 'Julie'), ('courses', ['Math', 'Physics']), ('phone', '555-5555')])


In [24]:
for key in student:
    print(key)

name
courses
phone


In [26]:
for key, value in student.items():
    print(key, value)

name Julie
courses ['Math', 'Physics']
phone 555-5555
